"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _here from './here.bones.json'
import _timeline from './timeline.bones.json'
import _aboutme from './aboutme.bones.json'
import _skills from './skills.bones.json'
import _project from './project.bones.json'

registerBones({
  "here": _here,
  "timeline": _timeline,
  "aboutme": _aboutme,
  "skills": _skills,
  "project": _project,
})
