"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _hero from './hero.bones.json'
import _timeline from './timeline.bones.json'
import _aboutme from './aboutme.bones.json'
import _skills from './skills.bones.json'
import _project from './project.bones.json'
import _view_project from './view-project.bones.json'

registerBones({
  "hero": _hero,
  "timeline": _timeline,
  "aboutme": _aboutme,
  "skills": _skills,
  "project": _project,
  "view-project": _view_project,
})
